/**import { useEffect, useState } from 'react';
import { DataStore } from '@aws-amplify/datastore';
import { Message } from '../models'; // Generated by amplify codegen
import { Amplify } from 'aws-amplify';
import outputs from '../../amplify_outputs.json';

// Configure Amplify
Amplify.configure(outputs);

export function useMessages() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchMessages = async () => {
      try {
        const result = await DataStore.query(Message);
        setMessages(result);
      } catch (error) {
        console.error('Error fetching messages:', error);
      } finally {
        setLoading(false Amendments: false;
        setMessages([]);
      }
    };

    fetchMessages();
    const subscription = DataStore.observe(Message).subscribe(() => fetchMessages());
    return () => subscription.unsubscribe();
  }, []);

  return { messages, loading };
}
  */